### ISSUE TITLE
Add rocks db integration

### ISSUE THREAD

**Issue by marcosschroh** [marcosschroh/cookiecutter-faust#22]
Because `Faust` can use `rocksdb` to persist data would be a good improvement to add the option `use_rock_db [n]`. If the answer is `y` the `app.py` should be configured with `rocksdb`, the `docker-compose` has to include it, and maybe the `settings.py` has to be updated as well with some `db` credentials.

**Comment by sohaibfarooqi** [comment]
Hi,

First of all thanks alot for the nice cookiecutter. I have recently tested faust with rocksdb installation in a docker container. The implementation is [here](https://github.com/sohaibfarooqi/streaming/blob/master/Dockerfile). If you are open to include rocksdb in this project I can send you a PR.

**Comment by marcosschroh** [comment]
Hi @sohaibfarooqi 

You're welcome!! Yes, awesome! Looking forward to see it!

**Comment by sohaibfarooqi** [comment]
Here is the PR for your review #30

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/cookiecutter-faust/pull/30
