### ISSUE TITLE
Any new faust app is not autodiscovered

### ISSUE THREAD

**Issue by m3nd1s** [marcosschroh/cookiecutter-faust#32]
**Description**
I use cookiecutter-faust to generate a new project (with all default settings). Then I execute `make run-dev` which builds the image, and runs it in a container. I run bash inside the running container with `make bash` and run `SIMPLE_SETTINGS=my_awesome_faust_project.settings my_awesome_faust_project agents` which gives following output:
 
![1](https://user-images.githubusercontent.com/8137117/62210020-c4494000-b3b8-11e9-91ef-402acf6deb31.png)

I make another app folder in my `my_awesome_faust_project/` dir called `test_app` so that my project dir looks like this:
![2](https://user-images.githubusercontent.com/8137117/62210318-7c76e880-b3b9-11e9-874b-7ac30a9f51c1.png)

Here are the contents of my `test_app/agents.py`:
![3](https://user-images.githubusercontent.com/8137117/62210377-a7f9d300-b3b9-11e9-96a6-6ca5237fd083.png)

The contents of `test_app/models.py` is the same as `page_views/models.py`.

**ISSUE**
Now when I run `make clean` followed by `make run-dev` again, and then run `SIMPLE_SETTINGS=my_awesome_faust_project.settings my_awesome_faust_project agents` inside the container, the agents are the unchanged! Running `SIMPLE_SETTINGS=my_awesome_faust_project.settings my_awesome_faust_project models` yields
![4](https://user-images.githubusercontent.com/8137117/62210682-5b62c780-b3ba-11e9-958f-24e05da61bbd.png)

**Expected Output**
There is no mention of the newly created app `test_app` in models and it's defined agent `test_agent` in agents. 

What am I missing ??

**Comment by marcosschroh** [comment]
Hi @m3nd1s ,

Thanks for let me know. I will take a look on this.

**Comment by marcosschroh** [comment]
I have created a new project with all the default values and  the `autodiscover` works well.  Could you check whether the topic `test_app` exist? You can see the `topics` running `make list-topics`. Which kind of storage are you using? `RocksDB` or `Memory`?

**Comment by marcosschroh** [comment]
@m3nd1s 

Any progress on this?

**Comment by marcosschroh** [comment]
Closing this issue because it has been inactive. I can not reproduce it with the previous version `0.71` and the new one `0.7.2`

Please reopen if you still encounter this issue with the version

Thank you!
