### ISSUE TITLE
make build after make install not working

### ISSUE THREAD

**Issue by eracle** [marcosschroh/cookiecutter-faust#59]
Hey thanks for your time in creating this project.

**Describe the bug**
After having created a new project, I create a local env with: 
`make install` 

Then when using:
`make build` fails.

**Expected behavior**
To build smothly.

**Additional context**
I used with with or without rocksdb.

Here's the error message:
Step 7/11 : RUN make install-production
 ---> Running in 887ddb5a40e2
python3.7 -m venv ./venv
Error: [Errno 2] No such file or directory: '/project_name/venv/bin/python3.7': '/project_name/venv/bin/python3.7'
make: *** [Makefile:20: install-production] Error 1

**Proposed fix**
include `venv` in .dockerignore file or rename all venv as .venv so it would be docker ignored by default.

**Comment by marcosschroh** [comment]
closed by https://github.com/marcosschroh/cookiecutter-faust/pull/60
